### PR TITLE
Update references to /etc/mobile

### LINKED ISSUE #138: Update references to /etc/mobile
Update outdated references

### PR DESCRIPTION
**Pull request by vladbailescu**
(fixes #138)

### CODE REVIEW

**Comment by keepthebyte** [comment]
does that work on AEM 6.3? w

**Comment by vladbailescu** [comment]
@keepthebyte, I verified with 6.3 SP1 and the emulators are being picked correctly from `/etc/mobile/groups/responsive` with this change.

**Comment by vladbailescu** [comment]
@keepthebyte, you are actually right: relative paths are not supported in 6.3, they will be supported starting with 6.4.
However, given this is test content and our tests do not check responsive functionality (out of scope for the components) and pass with these changes, we would prefer to update the paths to the cleaner version, just in case new projects targeting 6.4 get inspiration from our content.

**Comment by kwin** [comment]
@vladbailescu If this really works only with AEM 6.4 at least a short comment should be placed in that test content.

**Comment by vladbailescu** [comment]
The content installs in 6.3 and produces no errors. However, using a relative path for for the responsive mobile groups will cause the mobile emulators to not load. Testing the emulators is not in scope of the core components so arguably the change _works_ for this project in 6.3 too.

**Pull request merged**
